# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'


- script: |
    cd client
    npm install
    npm run build
  displayName: 'npm install and build'
- script: | 
    mkdir -p $(Build.ArtifactStagingDirectory)
    cp -R ./* $(Build.ArtifactStagingDirectory)
  displayName: 'Copy files to Artifact Staging Directory'

#- task: ArchiveFiles@2
#  inputs:
 #   rootFolderOrFile: '$(Build.BinariesDirectory)'
  #  includeRootFolder: true
  #  archiveType: 'zip'
   # archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    #replaceExistingArchive: true
#displayName: 'Archive build artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
displayName: 'Publish build artifacts'
